# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SegmentAnything
                                 A QGIS plugin
 Segment Anything From Facebook Research
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-24
        copyright            : (C) 2024 by INF800
        email                : rakeshark22@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SegmentAnything class from file SegmentAnything.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    from .packages_installer_dialog import (
        check_required_packages_and_install_if_necessary,
    )

    check_required_packages_and_install_if_necessary(iface=iface)

    from .segment_anything import SegmentAnything

    return SegmentAnything(iface)
