# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SegmentAnythingDialog
                                 A QGIS plugin
 Segment Anything From Facebook Research
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-24
        git sha              : $Format:%H$
        copyright            : (C) 2024 by INF800
        email                : rakeshark22@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets


class InputDataLayerOption:
    FROM_POLYGON = "From Polygons"
    VISIBLE_PART = "Visible Part"
    ENTIRE_LAYER = "Entire Layer"


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'segment_anything_dialog_base.ui'))


class SegmentAnythingDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SegmentAnythingDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self._create_input_data_connections()
        self._setup_input_data_ui()


    def _hide_polygons_layer(self):
        is_visible = self.qmlcbInputDataLayerOption.currentText()==InputDataLayerOption.FROM_POLYGON
        self.qmlcbInputDataPolygonsLayer.setVisible(is_visible)
        self.lbInputDataPolygonsLayer.setVisible(is_visible)


    def _create_input_data_connections(self):
        self.qmlcbInputDataLayerOption.currentIndexChanged.connect(
            self._hide_polygons_layer
        )


    def _setup_input_data_ui(self):
        layer_options = [
            InputDataLayerOption.VISIBLE_PART,
            InputDataLayerOption.ENTIRE_LAYER,
            InputDataLayerOption.FROM_POLYGON,
        ]

        for option in layer_options:
            self.qmlcbInputDataLayerOption.addItem(option)